.DEFAULT_GOAL := help
BACKEND := backend

.PHONY: help install fmt lint type test test-cov up down logs ps migrate revision downgrade seed run openapi clean

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-12s %s\n", $$1, $$2}'

install: ## Install backend runtime + dev dependencies
	cd $(BACKEND) && pip install -r requirements.txt -r requirements-dev.txt

fmt: ## Format code (black + ruff --fix)
	cd $(BACKEND) && black app tests && ruff check --fix app tests

lint: ## Lint (ruff) and check formatting (black)
	cd $(BACKEND) && ruff check app tests && black --check app tests

type: ## Static type check (mypy)
	cd $(BACKEND) && mypy app

test: ## Run test suite
	cd $(BACKEND) && pytest

test-cov: ## Run tests with coverage report
	cd $(BACKEND) && pytest --cov=app --cov-report=term-missing --cov-report=xml

up: ## Start the full stack (api, postgres, redis, pgadmin)
	docker compose up --build -d

down: ## Stop the stack
	docker compose down

logs: ## Tail api logs
	docker compose logs -f api

ps: ## Show stack status
	docker compose ps

migrate: ## Apply database migrations
	cd $(BACKEND) && alembic upgrade head

revision: ## Create a new autogenerated migration: make revision m="message"
	cd $(BACKEND) && alembic revision --autogenerate -m "$(m)"

downgrade: ## Revert the last migration
	cd $(BACKEND) && alembic downgrade -1

seed: ## Run seeders
	cd $(BACKEND) && python -m app.cli seed run

run: ## Run the API locally (reload)
	cd $(BACKEND) && python -m app.cli serve --reload

openapi: ## Export the OpenAPI schema to backend/openapi.json
	cd $(BACKEND) && python -m app.cli openapi export --out openapi.json

clean: ## Remove caches and build artifacts
	cd $(BACKEND) && rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage coverage.xml htmlcov
